name: Databricks CI/CD Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

env:
#these will be different for your environment
  PROJECT_NAME: simple-databricks-ml-cicd

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu Linux image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python for Databricks CLI

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli  # Install Databricks CLI
        databricks --version  # Verify the installation

    - name: Dev Workspace Deployment
      run: |
        echo "${{ secrets.DEV_DATABRICKS_HOST}}
        ${{ secrets.DEV_DATABRICKS_TOKEN }}" | databricks configure --token --profile DEV
      
        databricks repos update --path /Repos/DEV/${{env.PROJECT_NAME}} --branch dev

        # Do this only if you use Databrics notebooks
        # databricks workspace import_dir -o . /Workspace/Shared/DEV/${{ env.PROJECT_NAME}} --profile DEV  

        # Additional commands for running Dev workspace tests, etc.

    - name: QA Workspace Deployment
      run: |
        echo "${{ secrets.QA_DATABRICKS_HOST}}
        ${{ secrets.QA_DATABRICKS_TOKEN }}" | databricks configure --token --profile QA
      
        databricks repos update --path /Repos/QA/${{env.PROJECT_NAME}} --branch qa
        
        # Do this only if you use Databrics notebooks
        #databricks workspace import_dir -o . /Workspace/Shared/QA/${{ env.PROJECT_NAME}} --profile QA # Import code to QA workspace

        # Additional commands for running QA workspace tests, etc.

    - name: Prod Workspace Deployment
      run: |

        echo "${{ secrets.PROD_DATABRICKS_HOST}}
        ${{ secrets.PROD_DATABRICKS_TOKEN }}" | databricks configure --token --profile PROD

        databricks repos update --path /Repos/PROD/${{env.PROJECT_NAME}} --branch main
        # Do this only if you use Databrics notebooks
        #databricks workspace import_dir -o . /Workspace/Shared/PROD/${{ env.PROJECT_NAME}} --profile PROD # Import code to Prod workspace
        # Additional commands for running Prod workspace tests, etc.