name: Databricks CI/CD Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

env:
#these will be different for your environment
  PROJECT_NAME: simple-databricks-ml-cicd

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu Linux image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python for Databricks CLI

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli  # Install Databricks CLI
        databricks --version  # Verify the installation

    - name: Dev Workspace Deployment
      run: |
        databricks configure --token  ${{ secrets.DEV_DATABRICKS_TOKEN }} --url ${{ secrets.DEV_DATABRICKS_HOST }}  # Configure Databricks CLI with Dev workspace credentials
        databricks workspace import_dir . /Repos/DEV/${{ env.PROJECT_NAME}}  # Import code to Dev workspace
        # Additional commands for running Dev workspace tests, etc.

    - name: QA Workspace Deployment
      run: |
        databricks configure --token  ${{ secrets.QA_DATABRICKS_TOKEN }} --url ${{ secrets.QA_DATABRICKS_HOST }} # Configure Databricks CLI with QA workspace credentials
        databricks workspace import_dir . /Repos/QA/${{ env.PROJECT_NAME}}  # Import code to QA workspace
        # Additional commands for running QA workspace tests, etc.

    - name: Prod Workspace Deployment
      run: |
        databricks configure --token  ${{ secrets.PROD_DATABRICKS_TOKEN }} --url ${{ secrets.PROD_DATABRICKS_HOST }}  # Configure Databricks CLI with Prod workspace credentials
        databricks workspace import_dir . /Repos/PROD/${{ env.PROJECT_NAME}} # Import code to Prod workspace
        # Additional commands for running Prod workspace tests, etc.